# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.gandi.net/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.gandi.net.rb'

describe Whois::Record::Parser::WhoisGandiNet, "status_registered.expected" do

  subject do
    file = fixture("responses", "whois.gandi.net/status_registered.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    described_class.new(part)
  end

  describe "#disclaimer" do
    it do
      subject.disclaimer.should == "GANDI Registrar whois database for .COM, .NET, .ORG., .INFO, .BIZ, .NAME\nAccess and use restricted pursuant to French law on personal data. Copy of whole or part of the data without permission from GANDI is strictly forbidden. The sole owner of a domain is the entity described in the relevant 'domain:' record. Domain ownership disputes should be settled using ICANN's Uniform Dispute Resolution Policy: http://www.icann.org/udrp/udrp.htm For inquiries about 'by policy' protection, please check directly with the appropriate registry (Eurid, AFNIC, Red.es)\nAcces et utilisation soumis a la legislation francaise sur les donnees personnelles. Copie de tout ou partie de la base interdite sans autorisation de GANDI. Le possesseur d'un domaine est l'entite decrite dans l'enregistrement 'domain:' correspondant. Un desaccord sur la possession d'un nom de domaine peut etre resolu en suivant la Uniform Dispute Resolution Policy de l'ICANN: http://www.icann.org/udrp/udrp.htm Pour obtenir les informations en status 'Protected by policy', contactez directement le registre concerne (Eurid, AFNIC, Red.es)"
    end
  end
  describe "#domain" do
    it do
      subject.domain.should == "gandi.net"
    end
  end
  describe "#domain_id" do
    it do
      lambda { subject.domain_id }.should raise_error(Whois::AttributeNotSupported)
    end
  end
  describe "#available?" do
    it do
      subject.available?.should == false
    end
  end
  describe "#registered?" do
    it do
      subject.registered?.should == true
    end
  end
  describe "#created_on" do
    it do
      subject.created_on.should be_a(Time)
      subject.created_on.should == Time.parse("2000-02-23 12:12:59")
    end
  end
  describe "#expires_on" do
    it do
      subject.expires_on.should be_a(Time)
      subject.expires_on.should == Time.parse("2023-05-21 14:09:56")
    end
  end
  describe "#updated_on" do
    it do
      subject.updated_on.should be_a(Time)
      subject.updated_on.should == Time.parse("2013-06-17 11:07:35")
    end
  end
  describe "#registrar" do
    it do
      subject.registrar.should be_a(Whois::Record::Registrar)
      subject.registrar.id.should           == nil
      subject.registrar.name.should         == "GANDI Registrar"
      subject.registrar.organization.should == "GANDI Registrar"
      subject.registrar.url.should          == nil
    end
  end
  describe "#registrant_contacts" do
    it do
      subject.registrant_contacts.should be_a(Array)
      subject.registrant_contacts.should have(1).item
      subject.registrant_contacts[0].should be_a(Whois::Record::Contact)
      subject.registrant_contacts[0].type.should          == Whois::Record::Contact::TYPE_REGISTRANT
      subject.registrant_contacts[0].id.should            == "GS1833-GANDI"
      subject.registrant_contacts[0].name.should          == "Stephan Ramoin"
      subject.registrant_contacts[0].organization.should  == "Gandi SAS"
      subject.registrant_contacts[0].address.should       == "63-65 Boulevard Massena"
      subject.registrant_contacts[0].city.should          == "Paris"
      subject.registrant_contacts[0].zip.should           == "75013"
      subject.registrant_contacts[0].country.should       == "France"
      subject.registrant_contacts[0].country_code.should  == nil
      subject.registrant_contacts[0].phone.should         == "+33.143737851"
      subject.registrant_contacts[0].fax.should           == "+33.143731851"
      subject.registrant_contacts[0].email.should         == "61ebd5b3df9f45f2b3f67f6dd01e1049-523678@contact.gandi.net"
      subject.registrant_contacts[0].updated_on.should    == Time.parse("2013-08-13 10:23:30")
    end
  end
  describe "#admin_contacts" do
    it do
      subject.admin_contacts.should be_a(Array)
      subject.admin_contacts.should have(1).item
      subject.admin_contacts[0].should be_a(Whois::Record::Contact)
      subject.admin_contacts[0].type.should          == Whois::Record::Contact::TYPE_ADMINISTRATIVE
      subject.admin_contacts[0].id.should            == "NG270-GANDI"
      subject.admin_contacts[0].name.should          == "NOC GANDI"
      subject.admin_contacts[0].organization.should  == "GANDI SAS"
      subject.admin_contacts[0].address.should       == "63-65 Boulevard MASSENA"
      subject.admin_contacts[0].city.should          == "Paris"
      subject.admin_contacts[0].zip.should           == "75013"
      subject.admin_contacts[0].country.should       == "France"
      subject.admin_contacts[0].country_code.should  == nil
      subject.admin_contacts[0].phone.should         == "+33.143737851"
      subject.admin_contacts[0].fax.should           == "+33.143731851"
      subject.admin_contacts[0].email.should         == "12e7da77f638acdf8d9f4d0b828ca80c-248842@contact.gandi.net"
      subject.admin_contacts[0].updated_on.should    == Time.parse("2013-04-04 15:53:42")
    end
  end
  describe "#technical_contacts" do
    it do
      subject.technical_contacts.should be_a(Array)
      subject.technical_contacts.should have(1).item
      subject.technical_contacts[0].should be_a(Whois::Record::Contact)
      subject.technical_contacts[0].type.should          == Whois::Record::Contact::TYPE_TECHNICAL
      subject.technical_contacts[0].id.should            == "NG270-GANDI"
      subject.technical_contacts[0].name.should          == "NOC GANDI"
      subject.technical_contacts[0].organization.should  == "GANDI SAS"
      subject.technical_contacts[0].address.should       == "63-65 Boulevard MASSENA"
      subject.technical_contacts[0].city.should          == "Paris"
      subject.technical_contacts[0].zip.should           == "75013"
      subject.technical_contacts[0].country.should       == "France"
      subject.technical_contacts[0].country_code.should  == nil
      subject.technical_contacts[0].phone.should         == "+33.143737851"
      subject.technical_contacts[0].fax.should           == "+33.143731851"
      subject.technical_contacts[0].email.should         == "12e7da77f638acdf8d9f4d0b828ca80c-248842@contact.gandi.net"
      subject.technical_contacts[0].updated_on.should    == Time.parse("2013-04-04 15:53:42")
    end
  end
  describe "#nameservers" do
    it do
      subject.nameservers.should be_a(Array)
      subject.nameservers.should have(4).items
      subject.nameservers[0].should be_a(Whois::Record::Nameserver)
      subject.nameservers[0].name.should == "dns0.gandi.net"
      subject.nameservers[0].ipv4.should == "217.70.177.39"
      subject.nameservers[1].should be_a(Whois::Record::Nameserver)
      subject.nameservers[1].name.should == "dns1.gandi.net"
      subject.nameservers[1].ipv4.should == "217.70.177.45"
      subject.nameservers[2].should be_a(Whois::Record::Nameserver)
      subject.nameservers[2].name.should == "dns2.gandi.net"
      subject.nameservers[2].ipv4.should == "217.70.183.211"
      subject.nameservers[3].should be_a(Whois::Record::Nameserver)
      subject.nameservers[3].name.should == "dns3.gandi.net"
      subject.nameservers[3].ipv4.should == "217.70.179.36"
    end
  end
end
