# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.it/property_contact_province.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.nic.it.rb'

describe Whois::Record::Parser::WhoisNicIt, "property_contact_province.expected" do

  subject do
    file = fixture("responses", "whois.nic.it/property_contact_province.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    described_class.new(part)
  end

  describe "#registrant_contacts" do
    it do
      subject.registrant_contacts.should be_a(Array)
      subject.registrant_contacts.should have(1).items
      subject.registrant_contacts[0].should be_a(Whois::Record::Contact)
      subject.registrant_contacts[0].type.should         == Whois::Record::Contact::TYPE_REGISTRANT
      subject.registrant_contacts[0].id.should           == "HTML1-ITNIC"
      subject.registrant_contacts[0].name.should         == "HTML.it srl"
      subject.registrant_contacts[0].organization.should == "HTML.it srl"
      subject.registrant_contacts[0].address.should      == "Viale Alessandrino, 595"
      subject.registrant_contacts[0].city.should         == "Roma"
      subject.registrant_contacts[0].zip.should          == "00172"
      subject.registrant_contacts[0].state.should        == "RM"
      subject.registrant_contacts[0].country_code.should == "IT"
      subject.registrant_contacts[0].created_on.should   == Time.parse("2007-03-01 10:28:08")
      subject.registrant_contacts[0].updated_on.should   == Time.parse("2007-03-01 10:28:08")
    end
  end
end
