# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.hu/schema-1.99/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.nic.hu.rb'

describe Whois::Record::Parser::WhoisNicHu, "status_registered.expected" do

  before(:each) do
    file = fixture("responses", "whois.nic.hu/schema-1.99/status_registered.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  describe "#disclaimer" do
    it do
      @parser.disclaimer.should == "Rights restricted by copyright. Szerzõi jog fenntartva.\n-Legal usage of this service requires that you agree to\nabide by the rules and conditions set forth at\nhttp://www.domain.hu/domain/English/domainsearch/feltetelek.html\n-A szolgaltatas csak a\nhttp://www.domain.hu/domain/domainsearch/feltetelek.html címen\nelérhetõ feltételek elfogadása és betartása mellett\nhasználható legálisan."
    end
  end
  describe "#domain" do
    it do
      @parser.domain.should == "google.hu"
    end
  end
  describe "#domain_id" do
    it do
      @parser.domain_id.should == "0000219547"
    end
  end
  describe "#status" do
    it do
      @parser.status.should == :registered
    end
  end
  describe "#available?" do
    it do
      @parser.available?.should == false
    end
  end
  describe "#registered?" do
    it do
      @parser.registered?.should == true
    end
  end
  describe "#created_on" do
    it do
      @parser.created_on.should be_a(Time)
      @parser.created_on.should == Time.parse("2000-03-25 23:20:39")
    end
  end
  describe "#updated_on" do
    it do
      @parser.updated_on.should be_a(Time)
      @parser.updated_on.should == Time.parse("2009-08-25 10:11:32")
    end
  end
  describe "#expires_on" do
    it do
      lambda { @parser.expires_on }.should raise_error(Whois::PropertyNotSupported)
    end
  end
  describe "#registrar" do
    it do
      @parser.registrar.should be_a(Whois::Record::Registrar)
      @parser.registrar.id.should           == "1960108002"
      @parser.registrar.name.should         == "3C Kft. CLASS(registrar)"
      @parser.registrar.organization.should == "3C Ltd."
    end
  end
  describe "#registrant_contacts" do
    it do
      @parser.registrant_contacts.should be_a(Array)
      @parser.registrant_contacts.should have(1).items
      @parser.registrant_contacts[0].should be_a(Whois::Record::Contact)
      @parser.registrant_contacts[0].type.should         == Whois::Record::Contact::TYPE_REGISTRANT
      @parser.registrant_contacts[0].id.should           == nil
      @parser.registrant_contacts[0].name.should         == "Google, Inc."
      @parser.registrant_contacts[0].organization.should == "Google, Inc."
      @parser.registrant_contacts[0].address.should      == "Amphitheatre Pkwy 1600."
      @parser.registrant_contacts[0].city.should         == "Mountain View"
      @parser.registrant_contacts[0].zip.should          == "CA-94043"
      @parser.registrant_contacts[0].state.should        == nil
      @parser.registrant_contacts[0].country_code.should == "US"
      @parser.registrant_contacts[0].phone.should        == "+1 650 253 0000"
      @parser.registrant_contacts[0].fax.should          == "+1 650 253 0001"
      @parser.registrant_contacts[0].email.should        == nil
    end
  end
  describe "#admin_contacts" do
    it do
      @parser.admin_contacts.should be_a(Array)
      @parser.admin_contacts.should have(1).items
      @parser.admin_contacts[0].should be_a(Whois::Record::Contact)
      @parser.admin_contacts[0].type.should         == Whois::Record::Contact::TYPE_ADMIN
      @parser.admin_contacts[0].id.should           == "2000466366"
      @parser.admin_contacts[0].name.should         == "3C Kft. CLASS(registrar)"
      @parser.admin_contacts[0].organization.should == nil
      @parser.admin_contacts[0].address.should      == "Konkoly Thege út 29-33."
      @parser.admin_contacts[0].city.should         == "Budapest"
      @parser.admin_contacts[0].zip.should          == "H-1121"
      @parser.admin_contacts[0].state.should        == nil
      @parser.admin_contacts[0].country_code.should == "HU"
      @parser.admin_contacts[0].phone.should        == "+36 1 275 52 00"
      @parser.admin_contacts[0].fax.should          == "+36 1 275 58 87"
    end
  end
  describe "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
      @parser.technical_contacts.should have(1).items
      @parser.technical_contacts[0].should be_a(Whois::Record::Contact)
      @parser.technical_contacts[0].type.should         == Whois::Record::Contact::TYPE_TECHNICAL
      @parser.technical_contacts[0].id.should           == "2000578125"
      @parser.technical_contacts[0].name.should         == "Markmonitor"
      @parser.technical_contacts[0].organization.should == nil
      @parser.technical_contacts[0].address.should      == "Overland Road 10400, PMB155"
      @parser.technical_contacts[0].city.should         == "Boise"
      @parser.technical_contacts[0].zip.should          == "ID-83709"
      @parser.technical_contacts[0].state.should        == nil
      @parser.technical_contacts[0].country_code.should == "US"
      @parser.technical_contacts[0].phone.should        == "+ 1 208 389 5798"
      @parser.technical_contacts[0].fax.should          == "+ 1 208 389 5771"
      @parser.technical_contacts[0].email.should        == "ccops@markmonitor.com"
    end
  end
  describe "#nameservers" do
    it do
      @parser.nameservers.should be_a(Array)
      @parser.nameservers.should have(4).items
      @parser.nameservers[0].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[0].name.should == "ns1.google.com"
      @parser.nameservers[1].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[1].name.should == "ns4.google.com"
      @parser.nameservers[2].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[2].name.should == "ns3.google.com"
      @parser.nameservers[3].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[3].name.should == "ns2.google.com"
    end
  end
  describe "#zone_contact" do
    it do
      @parser.zone_contact.should be_a(Whois::Record::Contact)
      @parser.zone_contact.type.should         == nil
      @parser.zone_contact.id.should           == "2000578125"
      @parser.zone_contact.name.should         == "Markmonitor"
      @parser.zone_contact.organization.should == nil
      @parser.zone_contact.address.should      == "Overland Road 10400, PMB155"
      @parser.zone_contact.city.should         == "Boise"
      @parser.zone_contact.zip.should          == "ID-83709"
      @parser.zone_contact.state.should        == nil
      @parser.zone_contact.country_code.should == "US"
      @parser.zone_contact.phone.should        == "+ 1 208 389 5798"
      @parser.zone_contact.fax.should          == "+ 1 208 389 5771"
      @parser.zone_contact.email.should        == "ccops@markmonitor.com"
    end
  end
  describe "#registrar_contact" do
    it do
      @parser.registrar_contact.should be_a(Whois::Record::Contact)
      @parser.registrar_contact.type.should         == nil
      @parser.registrar_contact.id.should           == "1960108002"
      @parser.registrar_contact.name.should         == "3C Kft. CLASS(registrar)"
      @parser.registrar_contact.organization.should == "3C Ltd."
      @parser.registrar_contact.address.should      == "Konkoly Thege út 29-33."
      @parser.registrar_contact.city.should         == "Budapest"
      @parser.registrar_contact.zip.should          == "H-1121"
      @parser.registrar_contact.state.should        == nil
      @parser.registrar_contact.country_code.should == "HU"
      @parser.registrar_contact.phone.should        == "+36 1 275 52 00"
      @parser.registrar_contact.fax.should          == "+36 1 275 58 87"
    end
  end
end
