# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/whois/answer/parser/responses/whois.dns.be/property_nameservers_with_ip_spec.rb
#
# and regenerate the tests with the following rake task
#
#   $ rake genspec:parsers
#

require 'spec_helper'
require 'whois/answer/parser/whois.dns.be.rb'

describe Whois::Answer::Parser::WhoisDnsBe, "property_nameservers_with_ip.expected" do

  before(:each) do
    file = fixture("responses", "whois.dns.be/property_nameservers_with_ip.txt")
    part = Whois::Answer::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  context "#nameservers" do
    it do
      @parser.nameservers.should be_a(Array)
    end
    it do
      @parser.nameservers.should have(3).items
    end
    it do
      @parser.nameservers[0].should be_a(_nameserver)
    end
    it do
      @parser.nameservers[0].name.should == "ns3.register.be"
    end
    it do
      @parser.nameservers[0].ipv4.should == "91.121.5.186"
    end
    it do
      @parser.nameservers[1].should be_a(_nameserver)
    end
    it do
      @parser.nameservers[1].name.should == "ns1.register.be"
    end
    it do
      @parser.nameservers[1].ipv4.should == "80.169.63.207"
    end
    it do
      @parser.nameservers[2].should be_a(_nameserver)
    end
    it do
      @parser.nameservers[2].name.should == "ns2.register.be"
    end
    it do
      @parser.nameservers[2].ipv4.should == "194.78.23.152"
    end
  end
end
