# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/whois/answer/parser/responses/whois.nic.sn/status_registered_spec.rb
#
# and regenerate the tests with the following rake task
#
#   $ rake genspec:parsers
#

require 'spec_helper'
require 'whois/answer/parser/whois.nic.sn'

describe Whois::Answer::Parser::WhoisNicSn, "status_registered.expected" do

  before(:each) do
    file = fixture("responses", "whois.nic.sn/status_registered.txt")
    part = Whois::Answer::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  context "#registrar" do
    it do
      @parser.registrar.should be_a(_registrar)
    end
    it do
      @parser.registrar.id.should           == "registry"
    end
    it do
      @parser.registrar.name.should         == "registry"
    end
  end
  context "#registrant_contact" do
    it do
      @parser.registrant_contact.should be_a(_contact)
    end
    it do
      @parser.registrant_contact.type.should         == Whois::Answer::Contact::TYPE_REGISTRANT
    end
    it do
      @parser.registrant_contact.id.should           == "C4-SN"
    end
    it do
      @parser.registrant_contact.name.should         == "C4-SN"
    end
  end
  context "#admin_contact" do
    it do
      @parser.admin_contact.should be_a(_contact)
    end
    it do
      @parser.admin_contact.type.should         == Whois::Answer::Contact::TYPE_ADMIN
    end
    it do
      @parser.admin_contact.id.should           == "C5-SN"
    end
    it do
      @parser.admin_contact.name.should         == "C5-SN"
    end
  end
  context "#technical_contact" do
    it do
      @parser.technical_contact.should be_a(_contact)
    end
    it do
      @parser.technical_contact.type.should         == Whois::Answer::Contact::TYPE_TECHNICAL
    end
    it do
      @parser.technical_contact.id.should           == "C6-SN"
    end
    it do
      @parser.technical_contact.name.should         == "C6-SN"
    end
  end
end
