# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/whois/answer/parser/responses/whois.nic.it/property_technical_contact_spec.rb
#
# and regenerate the tests with the following rake task
#
#   $ rake genspec:parsers
#

require 'spec_helper'
require 'whois/answer/parser/whois.nic.it'

describe Whois::Answer::Parser::WhoisNicIt, "property_technical_contact.expected" do

  before(:each) do
    file = fixture("responses", "whois.nic.it/property_technical_contact.txt")
    part = Whois::Answer::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  context "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
    end
    it do
      @parser.technical_contacts.should have(1).items
    end
    it do
      @parser.technical_contacts[0].should be_a(_contact)
    end
    it do
      @parser.technical_contacts[0].type.should         == Whois::Answer::Contact::TYPE_TECHNICAL
    end
    it do
      @parser.technical_contacts[0].id.should           == "TS7016-ITNIC"
    end
    it do
      @parser.technical_contacts[0].name.should         == "Technical Services"
    end
  end
end
