# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/whois/answer/parser/responses/whois.nic.it/property_contact_with_organization_spec.rb
#
# and regenerate the tests with the following rake task
#
#   $ rake genspec:parsers
#

require 'spec_helper'
require 'whois/answer/parser/whois.nic.it.rb'

describe Whois::Answer::Parser::WhoisNicIt, "property_contact_with_organization.expected" do

  before(:each) do
    file = fixture("responses", "whois.nic.it/property_contact_with_organization.txt")
    part = Whois::Answer::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  context "#admin_contacts" do
    it do
      @parser.admin_contacts.should be_a(Array)
    end
    it do
      @parser.admin_contacts.should have(1).items
    end
    it do
      @parser.admin_contacts[0].should be_a(_contact)
    end
    it do
      @parser.admin_contacts[0].type.should         == Whois::Answer::Contact::TYPE_ADMIN
    end
    it do
      @parser.admin_contacts[0].id.should           == "TT4277-ITNIC"
    end
    it do
      @parser.admin_contacts[0].name.should         == "Tsao Tu"
    end
    it do
      @parser.admin_contacts[0].organization.should == "Tu Tsao"
    end
    it do
      @parser.admin_contacts[0].address.should      == "30 Herbert Street"
    end
    it do
      @parser.admin_contacts[0].city.should         == "Dublin"
    end
    it do
      @parser.admin_contacts[0].zip.should          == "2"
    end
    it do
      @parser.admin_contacts[0].state.should        == "IE"
    end
    it do
      @parser.admin_contacts[0].country_code.should == "IE"
    end
    it do
      @parser.admin_contacts[0].created_on.should   == Time.parse("2008-11-27 16:47:22")
    end
    it do
      @parser.admin_contacts[0].updated_on.should   == Time.parse("2008-11-27 16:47:22")
    end
  end
end
