# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/whois/answer/parser/responses/whois.nic.it/property_contact_with_company_in_address_spec.rb
#
# and regenerate the tests with the following rake task
#
#   $ rake genspec:parsers
#

require 'spec_helper'
require 'whois/answer/parser/whois.nic.it.rb'

describe Whois::Answer::Parser::WhoisNicIt, "property_contact_with_company_in_address.expected" do

  before(:each) do
    file = fixture("responses", "whois.nic.it/property_contact_with_company_in_address.txt")
    part = Whois::Answer::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  context "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
    end
    it do
      @parser.technical_contacts.should have(1).items
    end
    it do
      @parser.technical_contacts[0].should be_a(_contact)
    end
    it do
      @parser.technical_contacts[0].type.should         == Whois::Answer::Contact::TYPE_TECHNICAL
    end
    it do
      @parser.technical_contacts[0].id.should           == "AARS1-ITNIC"
    end
    it do
      @parser.technical_contacts[0].name.should         == "Andrea Antonio Renato Stratta"
    end
    it do
      @parser.technical_contacts[0].organization.should == "UCI Italia Srl"
    end
    it do
      @parser.technical_contacts[0].address.should      == "Via E. Fermi, 161"
    end
    it do
      @parser.technical_contacts[0].city.should         == "Roma"
    end
    it do
      @parser.technical_contacts[0].zip.should          == "00146"
    end
    it do
      @parser.technical_contacts[0].state.should        == "RM"
    end
    it do
      @parser.technical_contacts[0].country_code.should == "IT"
    end
    it do
      @parser.technical_contacts[0].created_on.should   == Time.parse("2006-08-16 00:00:00")
    end
    it do
      @parser.technical_contacts[0].updated_on.should   == Time.parse("2007-03-01 07:48:42")
    end
  end
end
