# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.educause.edu/property_contacts.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.educause.edu.rb'

describe Whois::Record::Parser::WhoisEducauseEdu, "property_contacts.expected" do

  subject do
    file = fixture("responses", "whois.educause.edu/property_contacts.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    described_class.new(part)
  end

  describe "#technical_contacts" do
    it do
      subject.technical_contacts.should be_a(Array)
      subject.technical_contacts.should have(1).items
      subject.technical_contacts[0].should be_a(Whois::Record::Contact)
      subject.technical_contacts[0].id.should            == nil
      subject.technical_contacts[0].name.should          == "Dennis L Noordam\nWindows System Administrator\nNorth Idaho College"
      subject.technical_contacts[0].organization.should  == nil
      subject.technical_contacts[0].address.should       == "1000 W. Garden Avenue"
      subject.technical_contacts[0].city.should          == "Coeur d Alene"
      subject.technical_contacts[0].zip.should           == "83814"
      subject.technical_contacts[0].state.should         == "ID"
      subject.technical_contacts[0].country.should       == "UNITED STATES"
      subject.technical_contacts[0].country_code.should  == nil
      subject.technical_contacts[0].phone.should         == "(208) 769-7860"
      subject.technical_contacts[0].fax.should           == nil
      subject.technical_contacts[0].email.should         == "dlnoordam@nic.edu"
    end
  end
end
