# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.educause.edu/property_contact_registrant_with_additional_organization.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.educause.edu.rb'

describe Whois::Record::Parser::WhoisEducauseEdu, "property_contact_registrant_with_additional_organization.expected" do

  subject do
    file = fixture("responses", "whois.educause.edu/property_contact_registrant_with_additional_organization.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    described_class.new(part)
  end

  describe "#registrant_contacts" do
    it do
      subject.registrant_contacts.should be_a(Array)
      subject.registrant_contacts.should have(1).items
      subject.registrant_contacts[0].should be_a(Whois::Record::Contact)
      subject.registrant_contacts[0].type.should          == Whois::Record::Contact::TYPE_REGISTRANT
      subject.registrant_contacts[0].id.should            == nil
      subject.registrant_contacts[0].name.should          == nil
      subject.registrant_contacts[0].organization.should  == "Harvard University"
      subject.registrant_contacts[0].address.should       == "HUIT Network Services\n60 Oxford Street"
      subject.registrant_contacts[0].city.should          == "Cambridge"
      subject.registrant_contacts[0].zip.should           == "02138"
      subject.registrant_contacts[0].state.should         == "MA"
      subject.registrant_contacts[0].country.should       == "UNITED STATES"
      subject.registrant_contacts[0].country_code.should  == nil
      subject.registrant_contacts[0].phone.should         == nil
      subject.registrant_contacts[0].fax.should           == nil
      subject.registrant_contacts[0].email.should         == nil
    end
  end
end
