#!/usr/bin/env ruby -wKU

$:.unshift(File.expand_path("../../lib", __FILE__))

require "fileutils"
require "whois"
require File.expand_path("../whois-utf8", __FILE__) rescue nil

d = ARGV.shift || raise("Missing domain")
n = ARGV.shift || raise("Missing file name")

r = Whois.query(d)

r.parts.each do |part|
  p = File.expand_path("../../spec/fixtures/responses/#{part.host}/#{n}", __FILE__)
  FileUtils.mkdir_p(File.dirname(p))
  File.open(p, "w+") { |f| f.write(part.body) }
  puts "Saved #{p}"
end
