#!/usr/bin/env ruby -wKU

$:.unshift(File.expand_path("../../lib", __FILE__))

require "fileutils"
require "whois"

d = ARGV.shift || raise("Missing domain")
n = ARGV.shift || raise("Missing file name")

r = Whois.query(d)

if r.parts.size == 1
  r.parts.each do |part|
    p = File.expand_path("../../test/testcases/responses/#{part.host}", __FILE__)
    FileUtils.mkdir_p(p)
    File.open("#{p}/#{n}", "w+") { |f| f.write(part.body) }
    puts "Saved #{p}/#{n}"
  end
else
  raise("Multipart")
end
