# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/whois/answer/parser/responses/whois.cnnic.cn/status_registered_spec.rb
#
# and regenerate the tests with the following rake task
#
#   $ rake genspec:parsers
#

require 'spec_helper'
require 'whois/answer/parser/whois.cnnic.cn'

describe Whois::Answer::Parser::WhoisCnnicCn, "status_registered.expected" do

  before(:each) do
    file = fixture("responses", "whois.cnnic.cn/status_registered.txt")
    part = Whois::Answer::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  context "#registrar" do
    it do
      @parser.registrar.should be_a(_registrar)
    end
    it do
      @parser.registrar.id.should           == "MarkMonitor, Inc."
    end
    it do
      @parser.registrar.name.should         == "MarkMonitor, Inc."
    end
    it do
      @parser.registrar.organization.should == nil
    end
  end
  context "#registrant_contact" do
    it do
      @parser.registrant_contact.should be_a(_contact)
    end
    it do
      @parser.registrant_contact.type.should         == Whois::Answer::Contact::TYPE_REGISTRANT
    end
    it do
      @parser.registrant_contact.id.should           == nil
    end
    it do
      @parser.registrant_contact.name.should         == "Domain Admin"
    end
    it do
      @parser.registrant_contact.organization.should == "Google Ireland Holdings"
    end
  end
  context "#admin_contact" do
    it do
      @parser.admin_contact.should be_a(_contact)
    end
    it do
      @parser.admin_contact.type.should         == Whois::Answer::Contact::TYPE_ADMIN
    end
    it do
      @parser.admin_contact.id.should           == nil
    end
    it do
      @parser.admin_contact.name.should         == nil
    end
    it do
      @parser.admin_contact.email.should        == "dns-admin@google.com"
    end
  end
  context "#technical_contact" do
    it do
      lambda { @parser.technical_contact }.should raise_error(Whois::PropertyNotSupported)
    end
  end
end
