# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.registry.net.za/property_registrant_empty_name.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.registry.net.za.rb'

describe Whois::Record::Parser::WhoisRegistryNetZa, "property_registrant_empty_name.expected" do

  subject do
    file = fixture("responses", "whois.registry.net.za/property_registrant_empty_name.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    described_class.new(part)
  end

  describe "#registrant_contacts" do
    it do
      expect(subject.registrant_contacts).to be_a(Array)
      expect(subject.registrant_contacts).to have(1).items
      expect(subject.registrant_contacts[0]).to be_a(Whois::Record::Contact)
      expect(subject.registrant_contacts[0].type).to eq(Whois::Record::Contact::TYPE_REGISTRANT)
      expect(subject.registrant_contacts[0].name).to eq("")
      expect(subject.registrant_contacts[0].email).to eq("steve@selftours.co.za")
      expect(subject.registrant_contacts[0].phone).to eq("+27.443841912")
      expect(subject.registrant_contacts[0].fax).to eq("+27.443840914")
      expect(subject.registrant_contacts[0].address).to eq("P.O. Box 2745 Knysna 6570\nKNYSNA\nZA\n6570")
    end
  end
end
