# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/whois/answer/parser/responses/whois.iana.org/status_not_assigned_spec.rb
#
# and regenerate the tests with the following rake task
#
#   $ rake genspec:parsers
#

require 'spec_helper'
require 'whois/answer/parser/whois.iana.org.rb'

describe Whois::Answer::Parser::WhoisIanaOrg, "status_not_assigned.expected" do

  before(:each) do
    file = fixture("responses", "whois.iana.org/status_not_assigned.txt")
    part = Whois::Answer::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  context "#registrant_contacts" do
    it do
      @parser.registrant_contacts.should be_a(Array)
    end
    it do
      @parser.registrant_contacts.should == []
    end
  end
  context "#admin_contacts" do
    it do
      @parser.admin_contacts.should be_a(Array)
    end
    it do
      @parser.admin_contacts.should == []
    end
  end
  context "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
    end
    it do
      @parser.technical_contacts.should == []
    end
  end
end
