# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.jprs.jp/ne.jp/property_state_reserved.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.jprs.jp.rb'

describe Whois::Record::Parser::WhoisJprsJp, "property_state_reserved.expected" do

  subject do
    file = fixture("responses", "whois.jprs.jp/ne.jp/property_state_reserved.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    described_class.new(part)
  end

  describe "#status" do
    it do
      subject.status.should == :reserved
    end
  end
  describe "#available?" do
    it do
      subject.available?.should == false
    end
  end
  describe "#registered?" do
    it do
      subject.registered?.should == true
    end
  end
  describe "#reserved?" do
    it do
      subject.reserved?.should == true
    end
  end
end
